# Generated by Django 4.2.2 on 2023-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format', models.TextField(max_length=8, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
